version: '3'
services:
  rust-instance:
    build: .
    ports: 
      - "3030:3030"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - nginx_net

  rust-instance-2:
    build: .
    ports: 
      - "3031:3030"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - nginx_net

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=30'
    networks:
      - nginx_net

  nginx:
    image: nginx
    ports: 
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rust-instance
      - rust-instance-2
    networks:
      - nginx_net

  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "arthur@tatay.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123456"
  #   ports:
  #     - "54321:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - nginx_net

networks:
  nginx_net: